module.exports = [
  {
    id: "1",
    url: "https://www.youtube.com/watch?v=Zlp3Aif6jJA",
    title: "ballet lesson",
    thumbnail: "/ballet-lesson.jpeg",
    year: "2023",
    type: "trending",
    bookmarked: "true",
  },
  {
    id: "2",
    url: "https://www.youtube.com/watch?v=JZJssSbjIJ0",
    title: "a trip to the moon",
    thumbnail: "/a-trip-to-the-moon.jpeg",
    year: "2023",
    type: "trending",
    bookmarked: "false",
  },
  {
    id: "3",
    url: "https://www.youtube.com/watch?v=...",
    title: "bicycle race",
    thumbnail: "/bicycle-race.jpeg",
    year: "2023",
    type: "trending",
    bookmarked: "false",
  },
  {
    id: "4",
    url: "https://www.youtube.com/watch?v=...",
    title: "daddy pig's lost keys",
    thumbnail: "/daddy-pigs-lost-keys.jpeg",
    year: "2023",
    type: "trending",
    bookmarked: "false",
  },
  {
    id: "5",
    url: "https://www.youtube.com/watch?v=...",
    title: "daddy pig's office",
    thumbnail: "/daddy-pigs-office.jpeg",
    year: "2023",
    type: "trending",
    bookmarked: "false",
  },
  {
    id: "6",
    url: "https://www.youtube.com/watch?v=...",
    title: "daddy pig's old chair",
    thumbnail: "/daddy-pigs-old-chair.jpeg",
    year: "2023",
    type: "trending",
    bookmarked: "false",
  },
  {
    id: "7",
    url: "https://www.youtube.com/watch?v=...",
    title: "dentist trip",
    thumbnail: "/dentist-trip.jpeg",
    year: "2023",
    type: "trending",
    bookmarked: "false",
  },
  {
    id: "8",
    url: "https://www.youtube.com/watch?v=...",
    title: "fun at the fair",
    thumbnail: "/fun-at-the-fair.jpeg",
    year: "2023",
    type: "trending",
    bookmarked: "false",
  },
  {
    id: "9",
    url: "https://www.youtube.com/watch?v=...",
    title: "george and the noisy baby",
    thumbnail: "/george-and-the-noisy-baby.jpeg",
    year: "2023",
    type: "trending",
    bookmarked: "false",
  },
  {
    id: "10",
    url: "https://www.youtube.com/watch?v=...",
    title: "george catches a cold",
    thumbnail: "/georges-catches-a-cold.jpeg",
    year: "2023",
    type: "trending",
    bookmarked: "false",
  },
  {
    id: "11",
    url: "https://www.youtube.com/watch?v=...",
    title: "george's balloon",
    thumbnail: "/georges-balloon.jpeg",
    year: "2023",
    type: "trending",
    bookmarked: "false",
  },
  {
    id: "12",
    url: "https://www.youtube.com/watch?v=...",
    title: "george's first day at playgroup",
    thumbnail: "/georges-first-day-at-playgroup.jpeg",
    year: "2023",
    type: "trending",
    bookmarked: "false",
  },
  {
    id: "13",
    url: "https://www.youtube.com/watch?v=...",
    title: "horsey twinkle toes",
    thumbnail: "/horsey-twinkle-toes.jpeg",
    year: "2023",
    type: "trending",
    bookmarked: "false",
  },
  {
    id: "14",
    url: "https://www.youtube.com/watch?v=...",
    title: "miss rabbit's day off",
    thumbnail: "/miss-rabbits-day-off.jpeg",
    year: "2023",
    type: "trending",
    bookmarked: "false",
  },
  {
    id: "15",
    url: "https://www.youtube.com/watch?v=...",
    title: "peppa goes on holiday",
    thumbnail: "/peppa-goes-on-holiday.jpeg",
    year: "2023",
    type: "trending",
    bookmarked: "false",
  },
  {
    id: "16",
    url: "https://www.youtube.com/watch?v=...",
    title: "peppa pig's family computer",
    thumbnail: "/peppa-pigs-family-computer.jpeg",
    year: "2023",
    type: "trending",
    bookmarked: "false",
  },
  {
    id: "17",
    url: "https://www.youtube.com/watch?v=...",
    title: "peppa plays basketball",
    thumbnail: "/peppa-plays-basketball.jpeg",
    year: "2023",
    type: "trending",
    bookmarked: "false",
  },
  {
    id: "18",
    url: "https://www.youtube.com/watch?v=...",
    title: "peppa's first glasses",
    thumbnail: "/peppas-first-glasses.jpeg",
    year: "2023",
    type: "trending",
    bookmarked: "false",
  },
  {
    id: "19",
    url: "https://www.youtube.com/watch?v=...",
    title: "the fancy dress party",
    thumbnail: "/the-fancy-dress-party.jpeg",
    year: "2023",
    type: "trending",
    bookmarked: "false",
  },
  {
    id: "20",
    url: "https://www.youtube.com/watch?v=...",
    title: "the toy cupboard",
    thumbnail: "/the-toy-cupboard.jpeg",
    year: "2023",
    type: "trending",
    bookmarked: "false",
  },
  {
    id: "21",
    url: "https://www.youtube.com/watch?v=...",
    title: "the wishing well",
    thumbnail: "/the-wishing-well.jpeg",
    year: "2023",
    type: "trending",
    bookmarked: "false",
  },
];
